DEVICE_PATH := device/xiaomi/obsidian

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a

# Kernel Config
BOARD_KERNEL_PAGESIZE := 4096
BOARD_BOOT_HEADER_VERSION := 4
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)

# Recovery Logic for A/B Device
BOARD_USES_RECOVERY_AS_BOOT := false
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true

# Partition Limits (DO NOT EXCEED 64MB)
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864

# Platform - MT6789 is the base ID for Helio G100
TARGET_BOARD_PLATFORM := mt6789

# Size Management (Ensures the build fits in 64MB)
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := false
TW_INCLUDE_CRYPTO := true
